name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run tests
      run: xcodebuild -project MyTest.xcodeproj  -scheme MyTest  test
